name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Install .NET
        uses: actions/setup-dotnet@aa983c550dfda0d1722b6ac6aed55724ffacc6d3
        with:
          dotnet-version: "7.0.100"

      - name: Run tests
        run: pwsh ./test.ps1
